### ISSUE TITLE
Compatibility with 4.19

### ISSUE THREAD

**Issue by hallo-w3lt** [Parallelcube/UE4_T-Outline#1]
Hi, excellent repo, but it has issues with 4.19 version.

Regards

**Comment by Parallelcube** [comment]
Hi
I have pushed the 4.19 fix. They have changed the ScreenPosition node to return the ViewportUV instead of the BufferUV in this version. 
https://issues.unrealengine.com/issue/UE-57416

sorry for the late reply, I need to configure some github alert 🔔
